version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2023.03
      
    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y \
              build-essential \
              gcc \
              make \
              flex \
              bison \
              libssl-dev \
              libelf-dev \
              bc

      # Configure your kernel build (adjust as needed)
      # Build the kernel
      - run:
          name: Build Kernel
          command: |
            make oldconfig
            make -j$(nproc) ARCH=arm64

      # Add more steps as needed, such as copying artifacts, running tests, etc.
      # ...

workflows:
  version: 2
  build:
    jobs:
      - build
