version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build-for-linux:
    docker: 
      - image: cimg/node:14.10.1
    steps:
      - checkout
      - run: make

workflows:
  version: 2.1
  build:
    jobs:
      - build-for-linux
